version: '3.4'

services:
  identity.core:
    image: ${DOCKER_REGISTRY-}identitycore
    restart: always
    build:
      context: .
      dockerfile: Identity.Core/Dockerfile
    ports:
      - "8060:80"
    depends_on:
      - db
      - es
    links:
      - es:elasticsearch

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - data:/var/lib/postgresql/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      # Add for elasticvue ↓
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:5602
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: Identity.Core
    depends_on:
      - es
    links:
      - es:elasticsearch

  elasticvue:
    image: cars10/elasticvue
    ports:
      - 5602:8080
    links:
      - es:elasticsearch
    

volumes:
  data: