version: '3.4'

services:
  identity.core:
    image: ${DOCKER_REGISTRY-}identitycore
    restart: always
    build:
      context: .
      dockerfile: Identity.Core/Dockerfile
    ports:
      - "8060:80"
    depends_on:
      - db
      - es
    links:
      - es:elasticsearch

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - data:/var/lib/postgresql/data

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: Identity.Core
    depends_on:
      - es
    links:
      - es:elasticsearch
    

volumes:
  data: